-- this will be for all other queries to test and run and carry out 
-- 'normal' operations on the database
USE publicworks;

SELECT * FROM DEPARTMENT;
SELECT * FROM JOB_TITLE;
SELECT * FROM CONTRACTOR;
SELECT * FROM EMPLOYEE;
SELECT * FROM INSPECTION;
SELECT * FROM CONSTRUCTION_CONTRACT;
SELECT * FROM ZONE;
SELECT * FROM PROJECT;
SELECT * FROM COUNTY_BANK_ACCOUNT;
SELECT * FROM INVOICE;
SELECT * FROM PERMIT;
SELECT * FROM VIOLATION;
SELECT * FROM WORKS_ON;
SELECT * FROM WORKED_ON;